Repository Vizzuality/foodscapes, pull requests merged in 2023-02, with the labels that each got.

#13 Feature/map
  client/package.json
  client/src/components/map/component.tsx
  client/src/containers/explore-map/component.tsx
  client/src/containers/sync-url/component.tsx
  client/src/containers/sync-url/index.ts
  client/src/pages/sync-url.tsx
  client/src/store/sync-url/index.ts
  client/yarn.lock
Labels: Frontend

#11 [FOOD-68] Landing: think of it in layers section
  client/public/images/layers/all.png
  client/public/images/layers/empty.png
  client/public/images/layers/management.png
  client/public/images/layers/physical.png
  client/public/images/layers/socio.png
  client/src/components/button/constants.ts
  client/src/containers/home/component.tsx
  client/src/containers/home/constants.ts
  client/src/containers/home/layers/button/component.tsx
  client/src/containers/home/layers/button/constants.ts
  client/src/containers/home/layers/button/index.ts
  client/src/containers/home/layers/button/types.d.ts
  client/src/containers/home/layers/component.tsx
  client/src/containers/home/layers/constants.tsx
  client/src/containers/home/layers/index.ts
  client/src/hooks/images-preloader/index.tsx
  client/tailwind.config.js
Labels: Frontend

#14 share path to DATA_HOME between docker build and app [FOOD-87]
  tiler/Dockerfile
  tiler/app/main.py
Labels: tiler

#16 Fix/think it of layers
  client/package.json
  client/src/components/map/component.tsx
  client/src/containers/explore-map/component.tsx
  client/src/containers/home/animations/constants.ts
  client/src/containers/home/animations/fadeY/component.tsx
  client/src/containers/home/animations/hooks/index.ts
  client/src/containers/home/circles/charts/component.tsx
  client/src/containers/home/circles/texts/component.tsx
  client/src/containers/home/constants.ts
  client/src/containers/home/hero/component.tsx
  client/src/containers/home/layers/button/component.tsx
  client/src/containers/home/layers/component.tsx
  client/yarn.lock
Labels: Frontend

#15 allow to configure whitelisted CORS origins [FOOD-108]
  ENV_VARS.md
  env.default
  tiler/app/main.py
  tiler/app/utils/__init__.py
  tiler/app/utils/cors_middleware.py
Labels: tiler

#23 (chore) sync sqlite import script to match latest data [FOOD-136]
  data/import/foodscapes/README.md
  data/import/foodscapes/foodscapes_sqlite-db-setup.sql
Labels: data

#28 Map feedback
  client/package.json
  client/src/constants/nav.ts
  client/src/containers/explore-map/menu/component.tsx
  client/yarn.lock
Labels: bug, Frontend
