Repository Vizzuality/foodscapes, pull requests merged in 2023-04, with the labels that each got.

#49 add AWS architecture diagram [FOOD-223]
  docs/high-level-architecture/aws-architecture.puml
  docs/high-level-architecture/aws_architecture.png
Labels: documentation

#47 Mobile/landing page
  client/public/images/layers/all.png
  client/public/images/layers/empty.png
  client/public/images/layers/management.png
  client/public/images/layers/physical.png
  client/public/images/layers/socio.png
  client/src/containers/datasets/foodscapes/hooks.ts
  client/src/containers/explore-map/component.tsx
  client/src/containers/explore-map/legend/component.tsx
  client/src/containers/explore-map/map/controls/menu/component.tsx
  client/src/containers/footer/index.tsx
  client/src/containers/header/app/component.tsx
  client/src/containers/header/menu/component.tsx
  client/src/containers/header/menu/constants.ts
  client/src/containers/header/menu/index.ts
  client/src/containers/home/circles/charts/component.tsx
  client/src/containers/home/circles/texts/text1/component.tsx
  client/src/containers/home/circles/texts/text2/component.tsx
  client/src/containers/home/circles/texts/text3/component.tsx
  client/src/containers/home/circles/texts/text4/component.tsx
  client/src/containers/home/component.tsx
  client/src/containers/home/globe/map/component.tsx
  client/src/containers/home/globe/text/component.tsx
  client/src/containers/home/hero/component.tsx
  client/src/containers/home/how/chart/component.tsx
  client/src/containers/home/how/component.tsx
  client/src/containers/home/how/text/component.tsx
  client/src/containers/home/layers/chart/component.tsx
  client/src/containers/home/layers/texts/text1/component.tsx
  client/src/containers/home/layers/texts/text2/component.tsx
  client/src/containers/home/layers/texts/text3/component.tsx
  client/src/containers/home/layers/texts/text4/component.tsx
  client/src/containers/home/outro/index.tsx
  client/src/containers/home/scroll/index.tsx
  client/src/store/explore-map/index.ts
  client/src/store/menu/index.ts
Labels: Frontend

#56 Top charts & Download
  client/.env.default
  client/README.md
  client/package.json
  client/src/components/charts/horizontal-bar/index.tsx
  client/src/components/loading/index.ts
  client/src/components/loading/index.tsx
  client/src/components/ui/collapsible/index.tsx
  client/src/containers/datasets/crops/chart/top.tsx
  client/src/containers/datasets/crops/widget.tsx
  client/src/containers/datasets/foodscapes-intensities/chart/top.tsx
  client/src/containers/datasets/foodscapes-intensities/widget.tsx
  client/src/containers/datasets/foodscapes/chart/top.tsx
  client/src/containers/datasets/foodscapes/widget.tsx
  client/src/containers/widget/header/index.tsx
  client/src/containers/widget/index.tsx
  client/src/containers/widget/top/index.tsx
  client/src/hooks/crops/data.json
  client/src/hooks/data/index.ts
  client/src/hooks/foodscapes-intensities/data.json
  client/src/svgs/ui/download.svg
  client/yarn.lock
Labels: enhancement, Frontend
